name: de-lambda-deployment

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    name: run-tests
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: add dependencies
        run: make requirements
      - name: setup dev environment
        run: make dev-setup
      - name: run test
        run: make run-checks


deploy-lambda:
   if: false # this will cause the job to be skipped - delete to enable
   name: deploy-lambda
   runs-on: ubuntu-latest
   needs: run-tests
   environment: dev
   steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Install Terraform
      uses: hashicorp/setup-terraform@v3
    - name: AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id : ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key : ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region : ${{ secrets.AWS_REGION }}
    - name: Terraform init
      working-directory: Terraform
      run: terraform init
    - name: Terraform plan
      working-directory: Terraform
      run: terraform plan
    - name: Terraform apply
      working-directory: Terraform
      run: terraform apply --auto-approve